---
- name: Konfigurasi vm-database
  hosts: database
  become: true

  vars:
    # --- Variabel Autentikasi Ansible (Penting!) ---
    ansible_user: vagrant
    ansible_password: vagrant

    # --- Variabel Database kamu ---
    db_name: kasrw
    db_user: kasrw_user
    db_password: "password123"
    db_host: "192.168.56.10"

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true

    - name: Install MySQL Server
      ansible.builtin.apt:
        name: mysql-server
        state: present

    - name: Install python3-mysqldb
      ansible.builtin.apt:
        name: python3-mysqldb
        state: present
        update_cache: yes

    - name: Memastikan MySQL berjalan
      ansible.builtin.service:
        name: mysql
        state: started
        enabled: true

    - name: Konfigurasi vm-frontend
  hosts: frontend
  become: true

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true

    - name: Install Nginx
      ansible.builtin.apt:
        name: nginx
        state: present

    - name: Memastikan Nginx berjalan
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true   
    
    - name: Buat halaman html sederhana
      ansible.builtin.copy:
        dest: /var/www/html/index.html
        content: "<html><body><h1>Selamat datang di vm-frontend</h1></body></html>"
        owner: www-data
        group: www-data
        mode: '0644'    